# frozen_string_literal: true

require 'fileutils'
require 'yaml'
require_relative 'rematch/source'
require_relative 'rematch/store'

# Handles the key/value store for each test file
class Rematch
  VERSION = '5.0.0'
  CONFIG  = { ext: '.yaml' }.freeze

  @rebuild      = false
  @rebuilt      = []
  @skip_warning = false
  @cache        = {} # Cache per file path: { source: Source, store: Store }

  class << self
    attr_accessor :rebuild, :skip_warning, :cache

    def check_rebuild(path)
      return unless @rebuild && !@rebuilt.include?(path)

      FileUtils.rm_f(path)
      @rebuilt << path
      puts "Rebuilt #{path}"
    end

    # Utility used by the plugin to extract label from args (kept for compatibility)
    def extract_label(args) = ((args.last.is_a?(Hash) && args.last.key?(:label) && args.pop) || {})[:label]

    # Get source and store for the test file (cached because invoked for every test in the file)
    def environment(path)
      cache[path] ||= begin
        store_path = "#{path}#{CONFIG[:ext]}"
        check_rebuild(store_path)
        source     = Source.new(File.read(path))
        source_ids = source.index.values.flatten.to_set
        store      = Store.new(store_path, source_ids)
        { source: source, store: store }
      end
    end
  end

  def initialize(test)
    @path     = test.method(test.name).source_location.first
    @env      = self.class.environment(@path)
    @counts   = Hash.new(0) # Track rematch counts per line
    @consumed = Hash.new { |h, k| h[k] = Set.new } # Track consumed INDICES per ID
  end

  # Retrieves the stored value for the current assertion, updating the store if the key is new or moved.
  def rematch(value, overwrite: nil, label: nil)
    lineno = caller_locations.find { |l| l.path == @path }&.lineno
    ids    = @env[:source].index[lineno]
    raise "Rematch Error: No code detected at #{@path}:#{lineno}. Please check the syntax." if ids.empty?

    count        = (@counts[lineno] += 1)
    id           = ids[(count - 1) % ids.size]
    store        = @env[:store]
    target_label = label ? label.to_s : 'rematch_value'

    # 1. Retrieve (and optionally rename) the entry list
    key     = "L#{lineno} #{id}"
    entries = store.ensure(id, key)

    # 2. Search for the first unconsumed entry matching the label
    match_index = entries.find_index.with_index do |entry, idx|
      next if @consumed[id].include?(idx)

      entry.key?(target_label)
    end

    # 3. Update or Append
    if match_index
      @consumed[id].add(match_index)
      stored_value = entries[match_index].values.first

      if stored_value != value && (overwrite || self.class.rebuild) # Update
        entries[match_index] = { target_label => value }
        warn_update(lineno)
        value
      else
        stored_value
      end
    else
      # New entry
      @consumed[id].add(entries.size)
      entries << { target_label => value }
      warn_update(lineno)
      value
    end
  end

  def save = @env[:store].save

  private

  def warn_update(lineno)
    warn "Rematch stored new value generated by: #{@path}:#{lineno}\n" unless self.class.skip_warning
  end
end
