# frozen_string_literal: true

require 'fileutils'
require 'yaml'
require_relative 'rematch/source'
require_relative 'rematch/store'

# Handles the key/value store for each test file
class Rematch
  VERSION = '5.0.0'
  CONFIG  = { ext: '.yaml' }.freeze

  @rebuild      = false
  @rebuilt      = []
  @skip_warning = false
  @cache        = {} # Cache per file path: { source: Source, store: Store }

  class << self
    attr_accessor :rebuild, :skip_warning, :cache

    def check_rebuild(path)
      return unless @rebuild && !@rebuilt.include?(path)

      FileUtils.rm_f(path)
      @rebuilt << path
      puts "Rebuilt #{path}"
    end

    # Utility used by the plugin to extract label from args (kept for compatibility)
    def extract_label(args) = ((args.last.is_a?(Hash) && args.last.key?(:label) && args.pop) || {})[:label]

    # Get source and store for the test file (cached because invoked for every test in the file)
    def environment(path)
      cache[path] ||= begin
        store_path = "#{path}#{CONFIG[:ext]}"
        check_rebuild(store_path)
        source     = Source.new(File.read(path))
        source_ids = source.index.values.flatten.to_set
        store      = Store.new(store_path, source_ids)
        { source: source, store: store }
      end
    end
  end

  def initialize(test)
    @path     = test.method(test.name).source_location.first
    @env      = self.class.environment(@path)
    @counts   = Hash.new(0) # Track rematch counts per line
    @consumed = Hash.new { |h, k| h[k] = Set.new } # Track consumed keys per ID
  end

  # Retrieves the stored value for the current assertion, updating the store if the key is new or moved.
  def rematch(value, overwrite: nil, label: nil)
    lineno = caller_locations.find { |l| l.path == @path }&.lineno
    ids    = @env[:source].index[lineno]
    raise "Rematch Error: No code detected at #{@path}:#{lineno}. Please check the syntax." if ids.empty?

    count   = (@counts[lineno] += 1)
    id      = ids[(count - 1) % ids.size]
    new_key = compose_key(lineno, count, label, id)
    store   = @env[:store]
    old_key = search_key(id, label)

    if old_key && old_key != new_key  # Reconcile Move first to ensure clean state
      store[new_key] = store.delete(old_key)
      @consumed[id].delete(old_key)
      @consumed[id].add(new_key)
      old_key = new_key # Normalize so we only check the overwrite logic below
    end

    if !old_key || overwrite
      warn "Rematch stored new value generated by: #{@path}:#{lineno}\n" unless overwrite || self.class.skip_warning
      store[new_key] = value
    else
      store[new_key]
    end
  end

  def save = @env[:store].save

  private

  def compose_key(lineno, count, label, id) = %(L#{lineno}#{".#{count}" if count > 1}#{" [#{label}]" if label} #{id})

  # Search for the next available key for this ID that hasn't been consumed by this test instance.
  def search_key(id, label)
    keys = @env[:store].keys(id)
    return unless keys

    key = keys.find do |k| # Find first non-consumed key for this ID
            next if @consumed[id].include?(k)

            !label || k.include?("[#{label}]")  # Respects labels if provided.
          end
    return unless key

    @consumed[id].add(key)
    key
  end
end
